### ISSUE TITLE
Missing CSV files

### ISSUE THREAD

**Issue by ratnanil** [RicardaFerrari/cma-exercise3#1]
https://github.com/RicardaFerrari/cma-exercise3/blob/536daf037e6464fc4f64ea7d0a6618b6756a2166/wk3-rexercise.R#L18-L19<br/><br/>Hi Ricarda, 

Please add `caro60.csv` and `pedestrian.csv` to the repo and close this issue after you have done so. See also https://github.com/RicardaFerrari/cma_exercise2/issues/4

Nils

**Comment by RicardaFerrari** [comment]
I have now added the two files

**Comment by ratnanil** [comment]
perfect, thank you!
